export const multiparous_dir = "multiparous"
export const nulliparous_dir = "nulliparous"
export const lmp_dir = "lmp"
export const empirical_data_dir = "empirical_data"
export const tif_dir = "total-demand"
export const geoplot_dir = "geo-plot"