version: '3.8'
services:
  mwh-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FILE_DB_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/databaseFileManager
        NEXT_PUBLIC_GEOBOUNDARY_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/geoboundary
        NEXT_PUBLIC_SAVE_SESSION_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/save_user_session
        NEXT_PUBLIC_LOAD_SESSION_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/get_user_session
        NEXT_PUBLIC_DATA_CONSOLIDATION_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/file-consolidation
        NEXT_PUBLIC_OPTIMIZATION_ENGINE_URL: https://30c2-94-46-236-217.ngrok-free.app/run-optimization
        NEXT_PUBLIC_DISTANCE_TO_ROAD_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/distance-to-road
        NEXT_PUBLIC_COST_MATRIX_URL: https://rxhlpn2bd8.execute-api.eu-west-2.amazonaws.com/dev/cost-matrix
        NEXT_PUBLIC_COST_OPTIMIZATION_URL: https://30c2-94-46-236-217.ngrok-free.app/process
    image: alnicole0103/mwh-frontend:v2
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=AKIA2XHEBIJJRPXVXAN5
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=eu-west-2